In [1]:
import tensorflow as tf

from gensim.models.keyedvectors import KeyedVectors
from konlpy.tag import Mecab

# from googletrans import Translator
from models.transformer import * 

import time
import numpy as np

import os
import sys
import urllib.request
import requests
import datetime
import pickle
import json

In [2]:
def embedding_load():
    """
    Load pretrained embedding vec
    """
    en_model = KeyedVectors.load_word2vec_format('./fasttext/wiki.en.vec')
    ko_model = KeyedVectors.load_word2vec_format('./fasttext/wiki.ko.vec')
    
    return en_model, ko_model

In [3]:
ko_model = KeyedVectors.load_word2vec_format('./fasttext/wiki.ko.vec')

In [6]:
encoder = Encoder(num_layers=1, d_model=1, num_heads=1, dff=512, input_vocab_size=0, maximum_position_encoding=0)
optimizer = tf.keras.optimizers.Adam(learning_rate=0.0001)

In [7]:
checkpoint_path = "./checkpoints/train"

ckpt = tf.train.Checkpoint(encoder=encoder,
                           optimizer=optimizer)

ckpt_manager = tf.train.CheckpointManager(ckpt, checkpoint_path, max_to_keep=5)

# if a checkpoint exists, restore the latest checkpoint.
if ckpt_manager.latest_checkpoint:
    ckpt.restore(ckpt_manager.latest_checkpoint)
    print('Latest checkpoint restored!!')

Latest checkpoint restored!!


In [16]:
trans_sample = list(ko_model.vocab)[:10000]

In [18]:
trans_vec = [ko_model.get_vector(i) for i in trans_sample]

In [23]:
trans_dict = {}
for idx in range(len(trans_sample)):
    trans_dict[trans_sample[idx]] = trans_vec[idx]

In [26]:
list(trans_dict.values())[0]

array([ 4.0987e-01,  5.3006e-03, -1.5832e+00, -1.0234e+00,  2.7239e-01,
       -1.2325e+00, -2.8500e-01, -5.9057e-01, -7.1622e-01, -7.8779e-01,
        4.6649e-02,  3.1382e-01, -4.1487e-01, -9.1984e-01, -3.0980e-01,
       -1.5516e-01,  8.1917e-02, -8.8866e-01, -2.6710e-02, -7.6736e-01,
        1.0054e+00, -2.7689e-01,  6.0095e-01, -6.6004e-02,  5.7456e-01,
        6.7092e-01, -1.4202e-01,  3.1292e-01, -8.1834e-01,  3.1503e-01,
        8.6697e-01, -9.3468e-01, -1.0193e+00,  3.2536e-01, -6.4223e-01,
       -7.6901e-01, -1.3965e+00, -1.2300e+00, -2.8656e-01, -3.4853e-01,
        1.0772e+00,  1.2494e+00,  3.3720e-01, -7.6690e-01,  6.3737e-01,
       -4.4553e-01,  5.1555e-01, -3.8258e-01,  8.6264e-01, -6.9718e-01,
        1.4699e+00,  6.7000e-01, -1.2923e+00, -1.0476e-01,  9.5305e-01,
        4.7174e-02,  1.0691e+00,  6.5087e-01,  1.4713e+00, -8.3216e-01,
        7.1885e-01,  1.8395e+00, -4.4246e-01,  3.1631e-01,  7.3043e-02,
       -1.9448e+00,  1.0989e+00, -2.6499e+00,  1.2871e+00, -1.23

In [30]:
encoder([list(trans_dict.values())[1]], training=False, mask=None)

Model Input shape (1, 300, 1)
Scaled_attention Shape :  (1, 1, 300, 1)
Scaled_attention Shape :  (1, 300, 1, 1)
Concat attention Shape : (1, 300, 1)


<tf.Tensor: shape=(1, 300, 1), dtype=float32, numpy=
array([[[0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
        [0.00854468],
 